version: '3.5'

services:
  backend:
    # You can also build your own image from the source or deploy in other ways, see further docs at https://gitlab.com/moodlenet/servers/federated/blob/develop/DEPLOY.md
    image: "moodlenet/moodlenet:latest"
    ports:
      - "4000:4000"
    env_file:
      - .env.backend
      - .env.secrets
    depends_on:
      - db
  frontend:
    build:
      context: .
#      dockerfile: "Dockerfile"
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./Caddyfile
        target: /etc/Caddyfile
        read_only: true
  db:
    image: postgres:9.6.6-alpine
    # volumes:
    #   - "./volumes/postgres:/var/lib/postgresql/data"
    # ports:
    #   - "5432:5432"
    env_file:
      - .env.backend
      - .env.secrets
